name: build-eadp-nifi-docker-images

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: trivadis/eadp-nifi
            dockerfile: nifi/1.27/Dockerfile
            context_dir: nifi/1.27            
            tag: 1.27.0
          - image: trivadis/eadp-nifi
            dockerfile: nifi/1.28/Dockerfile
            context_dir: nifi/1.28            
            tag: 1.28.0
          - image: trivadis/eadp-nifi
            dockerfile: nifi/2.0/Dockerfile
            context_dir: nifi/2.0
            tag: 2.0.0            
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3        
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{matrix.image}}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context_dir }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.image }}:${{ matrix.tag }}
